version: "3"

services:
  docusaurus-xracademy:
    image: "gmetrixr/baseimage:node-16-dev-v1"
    container_name: gmetri_docusaurus-xracademy
    command: ["tail", "-f", "/dev/null"]
    working_dir: /src
    user: node
    ports:
      - "8003:8003" #Format: HOST:CONTAINER
    volumes:
      - .:/src
    environment:
      - IS_LOCAL=true
      - BUILD_VERSION=localversion
      - NAMESPACE=local

networks:
  default:
    external:
      name: gmetri
